name: Build reference PDF

on:
  push:
    branches: [ master, testci ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build pdf
        uses: xu-cheng/latex-action@2.7.0
        with:
          working_directory: tex
          glob_root_file: true
          root_file: reference.tex
          
