name: Build reference PDF

on:
  push:
    branches: [ master, testci ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build PDF
        uses: actions/checkout@v2
        with:
          working_directory: tex
          root_file: reference.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: tex/main.pdf
          
