name: Build reference PDF

on:
  push:
    branches: [ master, testci ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: "./tex/reference.tex"
