name: Build reference PDF

on:
  push:
    branches: [ master, testci ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: xu-cheng/latex-action@v2
        with:
          working_directory: "/tex"
          root_file: "reference.tex"
